// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scrappy.Data;

#nullable disable

namespace Scrappy.Data.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260219144726_RemoveLevelUsersLevel")]
    partial class RemoveLevelUsersLevel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Scrappy.Data.Models.GuildConfig", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("AdminRoleId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("AppealLink")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<ulong?>("LevelUpChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("LogMessageEventChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("LogModerationEventChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("ModeratorRoleId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("WelcomeChannelId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("GuildId");

                    b.ToTable("GuildConfigs");
                });

            modelBuilder.Entity("Scrappy.Data.Models.Infraction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("IssuerId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<ulong>("TargetId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "CaseId")
                        .IsUnique();

                    b.HasIndex("GuildId", "IssuerId");

                    b.HasIndex("GuildId", "TargetId");

                    b.ToTable("Infractions");
                });

            modelBuilder.Entity("Scrappy.Data.Models.LevelUser", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<long>("TotalXp")
                        .HasColumnType("bigint");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "UserId")
                        .IsUnique();

                    b.ToTable("LevelUsers");
                });

            modelBuilder.Entity("Scrappy.Data.Models.Infraction", b =>
                {
                    b.HasOne("Scrappy.Data.Models.GuildConfig", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Scrappy.Data.Models.LevelUser", b =>
                {
                    b.HasOne("Scrappy.Data.Models.GuildConfig", "GuildConfig")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
